apiVersion: v1
kind: PersistentVolume
metadata:
  name: maven-pv
spec:
  storageClassName: maven-pv
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1.01Gi
  hostPath:
    path: "/data/maven-volume/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-pv-claim
  namespace: jenkins
spec:
  storageClassName: maven-pv
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce