apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
spec:
  storageClassName: jenkins-pv
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 11Gi
  hostPath:
    path: "/data/jenkins-volume/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  namespace: jenkins
spec:
  storageClassName: jenkins-pv
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
      namespace: jenkins
    spec:
      serviceAccountName: jenkins
      terminationGracePeriodSeconds: 10
      containers:
      - name: jenkins
        image: jenkins/jenkins:latest-jdk17
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 1Gi
            cpu: 1000m
          requests:
            memory: 256Mi
            cpu: 50m
        ports:
        - containerPort: 8080
          name: "http-port"
          protocol: TCP
        - containerPort: 50000
          name: "jnlp-port"
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 12 # ~2 minutes
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 12 # ~2 minutes
        env:
        - name: JAVA_OPTS
          value: -XshowSettings:vm -Dhudson.slaves.NodeProvisioner.initialDelay=0 -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85 -Duser.timezone=Asia/Shanghai
        volumeMounts:
        - mountPath: "/var/jenkins_home/"
          name: jenkins-vol
      volumes:
      - name: jenkins-vol
        persistentVolumeClaim: 
          claimName: jenkins-pv-claim
      securityContext:
        fsGroup: 1000

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
  - name: web
    port: 8080
    targetPort: 8080
    nodePort: 30080
  - name: slave
    port: 50000
    targetPort: 50000
    nodePort: 30081
            
