# 应用名称
spring:
  application:
    name: Web-Backend-Service
    version: 1.0.0-SNAPSHOT

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password: Alc@tel12
    hikari:
      # used for waiting MySQL container to startup
      initialization-fail-timeout: 10000

  jpa:
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    hibernate:
      # DB will be drop&create each time, initial data will be seeded by domain.repository.seeders.DataSeeder
      ddl-auto: create-drop

  # Html模板
  thymeleaf:
    cache: false  # 开发时关闭缓存，否则无法看到实时页面
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

  main:
    lazy-initialization: true   # 所有Bean将不在初始化时创建，而只在使用时才会创建

# 应用服务 WEB访问端口
server:
  port: 8080
  error:
    include-message: always

# 调试开关
debug: true
