apiVersion: v1
kind: Pod
metadata:
  name: builder
spec:
  containers:
  - name: kubectl
    image: joshendriks/alpine-k8s:latest
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "256Mi"
        cpu: "250m"
    command:
    - cat
    tty: true
  - name: git
    image: bitnami/git:latest
    imagePullPolicy: IfNotPresent
    command:
      - cat
    tty: true
  - name: maven
    image: maven:alpine
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: 1Gi
        cpu: "1000m"
      requests:
        memory: 512Mi
        cpu: "500m"
    command:
      - cat
    tty: true
    volumeMounts:
      - name: maven-cache
        mountPath: "/root/.m2"
  volumes:
    - name: maven-cache
      persistentVolumeClaim:
        claimName: maven-pv-claim